<a href="https://colab.research.google.com/github/2zoo99/tech_tutorials/blob/main/Numpy_Quick_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy 사용법  
numpy 는 배열이나 행렬 조작에 유용한 여러 함수를 제공해주는 파이썬 라이브러리이다.  
numpy 는 머신러닝 알고리즘을 다룰때 데이터 구조를 알기 위해 많이 사용된다.  
배열 또는 행렬은 python에서 `list` 로 생성하고,  
numpy 에서 `arrays` 로 생성하고,  
tensorflow 에서 `tensor`로 생성한다.  

## 1. Numpy 모듈을 가져온다.

In [1]:
import numpy as np

## 2. 사용자 지정 행렬을 만드는 `np.array`

In [2]:
one_dim_arr = np.array([1,2,4,5,7,8,0])

print(one_dim_arr)

[1 2 4 5 7 8 0]


In [4]:
two_dim_arr = np.array([[6,5],[9,11],[10,6]])

print(two_dim_arr)  # 3 x 2 array

[[ 6  5]
 [ 9 11]
 [10  6]]


In [6]:
all_zero_arr = np.zeros(10)     # 지정 개수만큼 요소값이 0인 1차원 배열

print(all_zero_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
all_one_arr = np.ones(10)       # 지정 개수만큼 요소값이 1인 1차원 배열

print(all_one_arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## 3. 지정 범위안의 정수 숫자들로 배열을 만드는 `np.arange`  (※ 'r' 두 개 아님 주의!)

In [9]:
seq_arr = np.arange(5,12)   # 5 이상 12 미만 범위의 연속 정수

print(seq_arr)

[ 5  6  7  8  9 10 11]


## 4. low, hige, size 지정값으로 해당 범위에 존재하는 랜덤 정수로 배열을 만드는 `np.random.randint`  (※ 컴파일마다 배열이 바뀜 주의! )

In [12]:
rand_arr = np.random.randint(50,101,(6,))     # np.random.randint(low=50, high=101, size=(6,)) 이렇게 작성해도 됨
                                              # 50 이상 101 미만 또는 50 이상 100 이하
print(rand_arr)

[51 69 54 50 82 89]


## 5. 0.0 부터 0.1 사이의 부동소수점 랜덤 실수로 배열을 만드는 `np.random.random`  ( size 지정값 필요 )

In [13]:
rand_float_arr = np.random.random((6,))

print(rand_float_arr)

[0.67746299 0.45076056 0.77760517 0.74168614 0.41601531 0.00489077]


## 6. 수학 연산자 또는 numpy 피연산자 모음

In [14]:
two_plus_rand_arr = rand_arr + 2    # 배열 전체 요소에 더하기 2
                                    # 또는 52 이상 103 미만 또는 52 이상 102 이하
print(two_plus_rand_arr)

[53 71 56 52 84 91]


In [15]:
two_plus_rand_float_arr = rand_float_arr + 2    # 또는 2.0

print(two_plus_rand_float_arr)

[2.67746299 2.45076056 2.77760517 2.74168614 2.41601531 2.00489077]


In [16]:
three_multiply_rand_arr = rand_arr * 3  # 배열 전체 요소에 곱하기 3

print(three_multiply_rand_arr)

[153 207 162 150 246 267]


## Task : create linear dataset  
1. 6이상 20이하의 연속 정수 배열 feature 만들기  
2. label = (3)(feature) + 4 의 형태처럼 feature 배열에 연산자를 적용한 label 만들기

In [18]:
feature = np.arange(6,21)

label = (feature * 3) + 4

print(feature)
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


## Task : add some noise to the dataset
1. 이미 만든 label 배열에 랜덤 noise 값을 몇개 추가하기  
2. noise는 -2 이상 2 이하의 부동소수점 랜덤 실수로 label 크기와 똑같이 구성하기

In [19]:
noise = (np.random.random((15,)) * 4) - 2
                                    # 디폴트가 0~1 사이의 실수니까 곱하기4 한 후에 뺴기 2하면 -2~2 사이의 실수
label = label + noise

print(noise)
print(label)

[ 0.50646185  1.76940045 -0.61257524  1.22800061 -0.00534849 -0.14957353
 -1.17935005 -1.05567216 -0.38537402 -0.24197079  1.31979134 -1.51603202
 -0.91097914 -0.38760178  1.48343857]
[22.50646185 26.76940045 27.38742476 32.22800061 33.99465151 36.85042647
 38.82064995 41.94432784 45.61462598 48.75802921 53.31979134 53.48396798
 57.08902086 60.61239822 65.48343857]
